name: Build RootX v6.0 Fast

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # --- 1. INSTALL TOOLS UTAMA UBUNTU (Wajib ada tiap build, tapi cepet) ---
      - name: Install System Prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install -y wget git flex bison gperf python3-pip python3-setuptools cmake ninja-build ccache libffi-dev libssl-dev dfu-util python3-venv

      # --- 2. CEK DAN AMBIL CACHE ESP-IDF ---
      - name: Cache ESP-IDF
        id: cache-idf
        uses: actions/cache@v4
        with:
          path: |
            ~/esp-idf
            ~/.espressif
          key: esp-idf-v6.0-${{ runner.os }}-v1
          save-always: true    # <--- TAMBAHIN BARIS INI COK!
          restore-keys: |
            esp-idf-v6.0-${{ runner.os }}-


      # --- 3. CLONE & INSTALL (Hanya jalan 1x pas pertama kali / kalau cache hangus) ---
      - name: Clone and Install ESP-IDF
        if: steps.cache-idf.outputs.cache-hit != 'true'
        run: |
          git clone -b v6.0 --depth 1 --recursive https://github.com/espressif/esp-idf.git ~/esp-idf
          ~/esp-idf/install.sh

      # --- 4. PATCHING SOURCE CODE (Tetap jalan biar file di dalam cache selalu ter-patch) ---
      - name: Patch gdbstub Source
        run: |
          python3 -c "import os,pathlib; p=pathlib.Path(os.path.expanduser('~/esp-idf'))/'components/esp_gdbstub/src/gdbstub.c'; s=p.read_text(encoding='utf-8'); s=s.replace('#if (CONFIG_ESP_SYSTEM_GDBSTUB_RUNTIME || CONFIG_ESP_GDBSTUB_SUPPORT_TASKS)', '#if 1'); p.write_text(s, encoding='utf-8')"
          
      - name: Build Firmware
        run: |
          # Load compiler & environment dari folder cache
          . ~/esp-idf/export.sh
          
          # Patching wifi_init
          python3 -c "import os; p=os.path.expanduser('~/esp-idf/components/esp_wifi/src/wifi_init.c'); \
          f=open(p,'r').read() if os.path.exists(p) else ''; \
          open(p,'w').write(f.replace('return ESP_ERR_WIFI_IF;', 'return ESP_OK;')) if f else print('File not found')"
          
          echo "Patch Selesai, Lanjut Build..."

          # Cek kalau sdkconfig lama ada biar ga build dari nol banget
          if [ -f sdkconfig.defaults ]; then
            cp sdkconfig.defaults sdkconfig
          fi
          
          idf.py set-target esp32s3
          idf.py build

      # --- 5. UPLOAD HASIL JADI .BIN ---
      - name: Upload Bin
        uses: actions/upload-artifact@v4
        with:
          name: RootX-v6-Firmware
          path: |
            build/RootX.bin
            build/bootloader/bootloader.bin
            build/partition_table/partition-table.bin
